site_name: Sonic World DX Mod Documentation
site_url: https://oakwoodwolf.github.io/swdx-mod-docs/
theme:
  favicon: img/favicon.ico
  logo: img/Mod.png
  features:
    - content.code.select
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  font:
    text: Roboto
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - mike
extra:
  generator: false
  version:
    alias: true
    provider: mike
nav:
  - Home: 
      - "Introduction":
          - "Welcome": index.md
          - "Mod Organization": modsxml.md
  - Characters:
      - "Guide":
          - "Fragmotion Animation Tutorial": Fragmotion/Animating.md
  - Themes:
      - "Guide":
          - "Installing": Theme/install.md
          - "Creating": Theme/creation.md
          - "Porting": Theme/porting.md
      - "File Reference":
          - "XMLs": Theme/themes.md
          - "Interface Index": Theme/Interface.md
          - "Sound Index": Theme/Sound.md
  - Stage:
      - "File Reference":
          - "Media": Stage/media.md
  - Music:
      - "Custom Music": Music/music.md
  - Discord: https://dc.railgun.works/sonicworlddx

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
